apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: crawl-validation
resources:
  - ../../../base/data-ingestor
images:
  - name: ghcr.io/hjyl-cheng/newcrawlsystem-runtime
    digest: sha256:ca4518a071e2878cdd932c5febaec36d36b1ba910c344b6949e10919257a8534
