apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: crawl-validation
resources:
  - ../../../base/data-ingestor
images:
  - name: ghcr.io/hjyl-cheng/newcrawlsystem-runtime
    digest: sha256:dedbc97c99a60d44596c0eb8b45f4109c3068e429389e0827dbc1617035f9dd9
