apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: [deployment.yaml, service.yaml, network-policy.yaml]
configMapGenerator:
- name: kafka-connect-config
  files: [worker.properties, log4j2.yaml]
