bootstrap.servers=10.4.4.2:9092,10.4.4.8:9092,10.4.4.5:9092
group.id=crawl-connect-cdc-validation
config.storage.topic=crawl.connect.validation.configs
offset.storage.topic=crawl.connect.validation.offsets
status.storage.topic=crawl.connect.validation.status
config.storage.replication.factor=3
offset.storage.replication.factor=3
status.storage.replication.factor=3
offset.storage.partitions=3
status.storage.partitions=3
key.converter=org.apache.kafka.connect.json.JsonConverter
key.converter.schemas.enable=false
value.converter=org.apache.kafka.connect.json.JsonConverter
value.converter.schemas.enable=false
plugin.path=/tmp/connect-plugins
listeners=http://0.0.0.0:8083
rest.advertised.host.name=${env:POD_IP}
rest.advertised.port=8083
config.providers=file,env
config.providers.file.class=org.apache.kafka.common.config.provider.FileConfigProvider
config.providers.env.class=org.apache.kafka.common.config.provider.EnvVarConfigProvider
config.providers.env.param.allowlist.pattern=POD_IP
offset.flush.interval.ms=1000
offset.flush.timeout.ms=10000
scheduled.rebalance.max.delay.ms=10000
session.timeout.ms=10000
heartbeat.interval.ms=3000
producer.acks=all
producer.enable.idempotence=true
producer.max.in.flight.requests.per.connection=5
connector.client.config.override.policy=None
topic.creation.enable=false
