apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: crawl-validation
resources:
  - ../../../base/runtime-smoke
images:
  - name: ghcr.io/hjyl-cheng/newcrawlsystem-runtime
    digest: sha256:686519af6766a49dc9a0410debc8d57b862dec416c5fee544a7dd595a0a6e74e
