modules:
  connect_status:
    metrics:
    - name: crawl_json_connect_connector_running
      path: '{.connector.state}'
      type: value
      help: Kafka Connect connector reports RUNNING
      values:
        RUNNING: 1
        PAUSED: 0
        FAILED: 0
        UNASSIGNED: 0
        RESTARTING: 0
        STOPPED: 0
    - name: crawl_json_connect_task_running
      type: object
      path: '{.tasks[*]}'
      help: One when a Kafka Connect task reports RUNNING
      labels:
        task_id: '{.id}'
        state: '{.state}'
      values:
        RUNNING: 1
        FAILED: 0
        PAUSED: 0
        UNASSIGNED: 0
        RESTARTING: 0
        STOPPED: 0
  ingestor_ready:
    metrics:
    - name: crawl_json_ingestor_ready
      path: '{.status}'
      type: value
      help: Data ingestor readiness reports ready
      values:
        ready: 1
        ok: 0
