global:
  scrape_interval: 30s
  scrape_timeout: 10s
  evaluation_interval: 15s
  external_labels:
    cluster: crawl-validation
    replica: ${POD_NAME}
rule_files:
- /etc/prometheus/rules.yaml
alerting:
  alert_relabel_configs:
  - action: labeldrop
    regex: replica
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager-0.alertmanager-headless:9093
      - alertmanager-1.alertmanager-headless:9093
      - alertmanager-2.alertmanager-headless:9093
scrape_configs:
- job_name: nodes
  scheme: https
  tls_config:
    ca_file: /etc/monitoring-tls/ca.crt
    cert_file: /etc/monitoring-tls/prometheus-client.crt
    key_file: /etc/monitoring-tls/prometheus-client.key
  static_configs:
  - targets:
    - 10.4.4.12:9100
    labels:
      node: a1
  - targets:
    - 10.4.4.3:9100
    labels:
      node: a2
  - targets:
    - 10.4.4.17:9100
    labels:
      node: a3
  - targets:
    - 10.4.4.2:9100
    labels:
      node: s1
  - targets:
    - 10.4.4.8:9100
    labels:
      node: s2
  - targets:
    - 10.4.4.5:9100
    labels:
      node: s3
- job_name: prometheus
  static_configs:
  - targets:
    - prometheus-0.prometheus-headless:9090
    - prometheus-1.prometheus-headless:9090
- job_name: alertmanager
  static_configs:
  - targets:
    - alertmanager-0.alertmanager-headless:9093
    - alertmanager-1.alertmanager-headless:9093
    - alertmanager-2.alertmanager-headless:9093
- job_name: kube-state-metrics
  static_configs:
  - targets:
    - kube-state-metrics:8080
- job_name: kafka-exporter
  static_configs:
  - targets:
    - kafka-exporter:9308
- job_name: infra-exporter
  static_configs:
  - targets:
    - infra-exporter:9189
- job_name: json-exporter
  static_configs:
  - targets:
    - json-exporter:7979
- job_name: blackbox-exporter
  static_configs:
  - targets:
    - blackbox-exporter:9115
- job_name: json
  metrics_path: /probe
  params:
    module:
    - '{module}'
  relabel_configs:
  - source_labels:
    - module
    target_label: __param_module
  - source_labels:
    - __address__
    target_label: __param_target
  - source_labels:
    - __param_target
    target_label: instance
  - target_label: __address__
    replacement: json-exporter:7979
  static_configs:
  - targets:
    - http://kafka-connect.crawl-validation.svc:8083/connectors/crawl-publication-validation/status
    labels:
      component: connect
      module: connect_status
  - targets:
    - http://data-ingestor.crawl-validation.svc:8080/health/ready
    labels:
      component: ingestor
      module: ingestor_ready
- job_name: blackbox
  metrics_path: /probe
  params:
    module:
    - http_2xx
  relabel_configs:
  - source_labels:
    - __address__
    target_label: __param_target
  - source_labels:
    - __param_target
    target_label: instance
  - target_label: __address__
    replacement: blackbox-exporter:9115
  static_configs:
  - targets:
    - http://data-ingestor.crawl-validation.svc:8080/health/live
    labels:
      component: ingestor
