apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
- vendor/install.yaml
- availability.yaml
images:
- name: quay.io/argoproj/argocd
  digest: sha256:dd3f47d5a5e4da563a7a398506e892481b358a7cec50abdf320c71aa55904bfa
- name: ghcr.io/dexidp/dex
  digest: sha256:8499afd690c437f52301efd2b05b2455da5bd2dfc20332cd697dc9937f808462
- name: public.ecr.aws/docker/library/redis
  newName: docker.io/library/redis
  digest: sha256:08ad0b1d280850169a790dba1393ff7a90aef951fc19632cf4d3ce4f78e679ba
- name: public.ecr.aws/docker/library/haproxy
  newName: docker.io/library/haproxy
  digest: sha256:e11f034e651603f10a365e5ad5a0321825e18eded9620e40c4f4d6ae58419bfe
patches:
- target:
    kind: Deployment
    name: argocd-applicationset-controller
  patch: "apiVersion: apps/v1\nkind: Deployment\nmetadata:\n  name: argocd-applicationset-controller\n\
    spec:\n  replicas: 1\n  template:\n    spec:\n      containers:\n      - name:\
    \ argocd-applicationset-controller\n        resources:\n          requests:\n\
    \            cpu: 10m\n            memory: 32Mi\n          limits:\n         \
    \   cpu: 250m\n            memory: 192Mi\n      nodeSelector:\n        node-role.kubernetes.io/control-plane:\
    \ ''\n      tolerations:\n      - key: node-role.kubernetes.io/control-plane\n\
    \        operator: Exists\n        effect: NoSchedule\n"
- target:
    kind: Deployment
    name: argocd-dex-server
  patch: "apiVersion: apps/v1\nkind: Deployment\nmetadata:\n  name: argocd-dex-server\n\
    spec:\n  replicas: 1\n  template:\n    spec:\n      containers:\n      - name:\
    \ dex\n        resources:\n          requests:\n            cpu: 10m\n       \
    \     memory: 32Mi\n          limits:\n            cpu: 250m\n            memory:\
    \ 192Mi\n      nodeSelector:\n        node-role.kubernetes.io/control-plane: ''\n\
    \      tolerations:\n      - key: node-role.kubernetes.io/control-plane\n    \
    \    operator: Exists\n        effect: NoSchedule\n"
- target:
    kind: Deployment
    name: argocd-notifications-controller
  patch: "apiVersion: apps/v1\nkind: Deployment\nmetadata:\n  name: argocd-notifications-controller\n\
    spec:\n  replicas: 1\n  template:\n    spec:\n      containers:\n      - name:\
    \ argocd-notifications-controller\n        resources:\n          requests:\n \
    \           cpu: 10m\n            memory: 32Mi\n          limits:\n          \
    \  cpu: 250m\n            memory: 192Mi\n      nodeSelector:\n        node-role.kubernetes.io/control-plane:\
    \ ''\n      tolerations:\n      - key: node-role.kubernetes.io/control-plane\n\
    \        operator: Exists\n        effect: NoSchedule\n"
- target:
    kind: Deployment
    name: argocd-redis-ha-haproxy
  patch: "apiVersion: apps/v1\nkind: Deployment\nmetadata:\n  name: argocd-redis-ha-haproxy\n\
    spec:\n  replicas: 2\n  template:\n    spec:\n      containers:\n      - name:\
    \ haproxy\n        resources:\n          requests:\n            cpu: 10m\n   \
    \         memory: 16Mi\n          limits:\n            cpu: 100m\n           \
    \ memory: 64Mi\n      nodeSelector:\n        node-role.kubernetes.io/control-plane:\
    \ ''\n      tolerations:\n      - key: node-role.kubernetes.io/control-plane\n\
    \        operator: Exists\n        effect: NoSchedule\n"
- target:
    kind: Deployment
    name: argocd-repo-server
  patch: "apiVersion: apps/v1\nkind: Deployment\nmetadata:\n  name: argocd-repo-server\n\
    spec:\n  replicas: 2\n  template:\n    spec:\n      containers:\n      - name:\
    \ argocd-repo-server\n        resources:\n          requests:\n            cpu:\
    \ 50m\n            memory: 128Mi\n          limits:\n            cpu: 500m\n \
    \           memory: 512Mi\n      nodeSelector:\n        node-role.kubernetes.io/control-plane:\
    \ ''\n      tolerations:\n      - key: node-role.kubernetes.io/control-plane\n\
    \        operator: Exists\n        effect: NoSchedule\n"
- target:
    kind: Deployment
    name: argocd-server
  patch: "apiVersion: apps/v1\nkind: Deployment\nmetadata:\n  name: argocd-server\n\
    spec:\n  replicas: 2\n  template:\n    spec:\n      containers:\n      - name:\
    \ argocd-server\n        resources:\n          requests:\n            cpu: 50m\n\
    \            memory: 64Mi\n          limits:\n            cpu: 500m\n        \
    \    memory: 384Mi\n      nodeSelector:\n        node-role.kubernetes.io/control-plane:\
    \ ''\n      tolerations:\n      - key: node-role.kubernetes.io/control-plane\n\
    \        operator: Exists\n        effect: NoSchedule\n"
- target:
    kind: StatefulSet
    name: argocd-application-controller
  patch: "apiVersion: apps/v1\nkind: StatefulSet\nmetadata:\n  name: argocd-application-controller\n\
    spec:\n  replicas: 1\n  template:\n    spec:\n      containers:\n      - name:\
    \ argocd-application-controller\n        resources:\n          requests:\n   \
    \         cpu: 100m\n            memory: 192Mi\n          limits:\n          \
    \  cpu: '1'\n            memory: 768Mi\n      nodeSelector:\n        node-role.kubernetes.io/control-plane:\
    \ ''\n      tolerations:\n      - key: node-role.kubernetes.io/control-plane\n\
    \        operator: Exists\n        effect: NoSchedule\n      affinity:\n     \
    \   nodeAffinity:\n          preferredDuringSchedulingIgnoredDuringExecution:\n\
    \          - weight: 100\n            preference:\n              matchExpressions:\n\
    \              - key: kubernetes.io/hostname\n                operator: In\n \
    \               values:\n                - a2\n"
- target:
    kind: StatefulSet
    name: argocd-redis-ha-server
  patch: "apiVersion: apps/v1\nkind: StatefulSet\nmetadata:\n  name: argocd-redis-ha-server\n\
    spec:\n  replicas: 3\n  template:\n    spec:\n      containers:\n      - name:\
    \ redis\n        resources:\n          requests:\n            cpu: 25m\n     \
    \       memory: 64Mi\n          limits:\n            cpu: 250m\n            memory:\
    \ 192Mi\n      - name: sentinel\n        resources:\n          requests:\n   \
    \         cpu: 10m\n            memory: 16Mi\n          limits:\n            cpu:\
    \ 100m\n            memory: 64Mi\n      - name: split-brain-fix\n        resources:\n\
    \          requests:\n            cpu: 5m\n            memory: 8Mi\n         \
    \ limits:\n            cpu: 100m\n            memory: 32Mi\n      nodeSelector:\n\
    \        node-role.kubernetes.io/control-plane: ''\n      tolerations:\n     \
    \ - key: node-role.kubernetes.io/control-plane\n        operator: Exists\n   \
    \     effect: NoSchedule\n"
